### ISSUE TITLE
Audience in JWT Token

### ISSUE THREAD

**Issue by mattiasmelin** [skolverket/dnp-usermanagement#18]
Accordning to https://github.com/skolverket/dnp-usermanagement/blob/main/authentication-api/README.md#verifiering-av-jwt-som-skickas-fr%C3%A5n-provtj%C3%A4nstens-ss12000-klient 
the audience should be "nutid"

"aud": "nutid",

Is this correct?

When we get a call from the test environment it seems to have some other audience.
I cannot see the audience at the moment since we do not log the JWT token.

**Comment by mattiasmelin** [comment]
Apparently it was using "nutid test".
It seems like your test environment is using the wrong authentication issuer:
https://nutid-auth-test.sunet.se
when it should be 
https://nutid-auth.sunet.se

**Comment by nighal** [comment]
The server URL for the test environment of the authorization server is https://nutid-auth-test.sunet.se, that's the reason why the issuer is set to https://nutid-auth-test.sunet.se. 
At the moment we are not using the "aud" claim. We might use it in the future to specify which client (organisation) the JWT is intended to.

**Comment by mattiasmelin** [comment]
We have check for allowed "aud" claims. Does this mean it can change at any time?

**Comment by mattiasmelin** [comment]
> The server URL for the test environment of the authorization server is https://nutid-auth-test.sunet.se, that's the reason why the issuer is set to https://nutid-auth-test.sunet.se. At the moment we are not using the "aud" claim. We might use it in the future to specify which client (organisation) the JWT is intended to.

But here: https://github.com/skolverket/dnp-usermanagement/blob/main/environments.md it says: 
"Notera att från och med den 15 mars 2024 ska det användas auktoriseringsservern i produktionsmiljö (https://nutid-auth.sunet.se/transaction)."

@nighal Which is correct?

**Comment by nighal** [comment]
> > The server URL for the test environment of the authorization server is https://nutid-auth-test.sunet.se, that's the reason why the issuer is set to https://nutid-auth-test.sunet.se. At the moment we are not using the "aud" claim. We might use it in the future to specify which client (organisation) the JWT is intended to.
> 
> But here: https://github.com/skolverket/dnp-usermanagement/blob/main/environments.md it says: "Notera att från och med den 15 mars 2024 ska det användas auktoriseringsservern i produktionsmiljö (https://nutid-auth.sunet.se/transaction)."
> 
> @nighal Which is correct?

The authorization server has a test environment (https://nutid-auth-test.sunet.se) where one can use a test certificate to fetch JWT. The JWT that is fetched cannot be used to verify provisioning. To test provisioning in verification test environment, School principals need to use their production certificate to fetch JWT from production environment (https://nutid-auth.sunet.se).
