### ISSUE TITLE
authentication-api was not published Q3-2021

### ISSUE THREAD

**Issue by NoSubstitute** [skolverket/dnp-usermanagement#4]
According to the readme, this API should have been published a year ago.

https://github.com/skolverket/dnp-usermanagement/blob/main/authentication-api/README.md

That didn't happen.

Makes it harder for people to prepare.

**Comment by mattiashyll** [comment]
> According to the readme, this API should have been published a year ago.
> 
> https://github.com/skolverket/dnp-usermanagement/blob/main/authentication-api/README.md
> 
> That didn't happen.
> 
> Makes it harder for people to prepare.

Hej kim,
Thanks for your comment. We have missed to update this date.

The official information about DNP is pubkushed here:
https://www.skolverket.se/om-oss/var-verksamhet/skolverkets-prioriterade-omraden/digitalisering/digitala-nationella-prov


Kind regards,
Mattias Hyll
Teamledare test och verifiering, Digitala Nationella Prov (DNP)

Skolverket, Förvaltning och Systemutveckling
Postadress: 106 20 Stockholm
Besöksadress: Svetsarvägen 16, Solna
Tfn: 46 (0) 733 984 108
mattias.hyll@skolverket.se

**Comment by NoSubstitute** [comment]
Ok, so when will the APIs be published?

**Comment by Tomerello** [comment]
Enligt skolverkets hemsida så pekar de på att vi hittar API dokumentationen här men när kan vi förvänta oss ett färdigt API så vi kan börja utveckla vår användar provisionering?

> "Notera att arbetet med digitala nationella prov (DNP) är ett pågående projekt och att materialet i DNP användarhantering uppdateras kontinuerligt. Det är inte fastställd information från Skolverket, utan dokumenten kommer att uppdateras."
