### ISSUE TITLE
Dokumentera autentiserings api:et

### ISSUE THREAD

**Issue by mikael-eventful** [skolverket/dnp-usermanagement#6]
Hej!

Dokumentationen för autentiserings api:et känns lite bristfällig. Skulle ni kunna uppdatera den med hur ni vill att autentiseringsförfarandet ska gå till?

**Comment by nighal** [comment]
Dokumentation för autentiserings API är nu uppdaterat. Se https://github.com/skolverket/dnp-usermanagement/tree/main/authentication-api.
